#!/bin/sh

mode=$1
if [[ -z $mode ]]; then mode=d; fi

if [ $mode = v ]; then
    out_dir=out/build/linux-debug/
    pushd ./$out_dir
        valgrind ./chibi-tech
    popd
    rm vgcore*
elif [ $mode = g ]; then
    out_dir=out/build/linux-debug/
    pushd ./$out_dir
        gdb --tui ./chibi-tech
    popd
else
    if [ $mode = d ]; then out_dir=out/build/linux-debug; fi
    if [ $mode = r ]; then out_dir=out/build/linux-release; fi

    pushd ./$out_dir
        ./chibi-tech
    popd
fi
