#!/bin/sh

mode=$1
if [[ -z $mode ]]; then mode=d; fi

# Set build directory
if [ $mode = d ]; then out_dir=out/build/linux-debug; fi
if [ $mode = r ]; then out_dir=out/build/linux-release; fi

pushd $out_dir
    ninja
popd
